1   # -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DyuRQewxMUsCkSnAxw3lBc3E3Hkz69YO
"""

from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive

drive.mount('/content/drive')



import matplotlib.pyplot as plt
import networkx as nx
from openpyxl import load_workbook
from networkx.exception import NetworkXNoPath

# Load the workbook and select the active sheet
wb = load_workbook('/content/drive/MyDrive/graph/data_26_thousand.xlsx')
ws = wb.active

# Extract nodes from the Excel file
nodes = []
G = nx.Graph()

for row in range(2, 1000):
    author = ws[f'B{row}'].value
    if author is not None:
        node1 = author
        node2 = ws[f'H{row}'].value
        if node2 is not None:
            names = [name.strip("'") for name in node2.split(", ")]
            for i in names:
                if i is not None and node1 is not None:
                    found = False
                    G.add_node(node1)

                    for n in nodes:
                        if n[1] == node1:
                            G.add_node(i)
                            G.add_edge(n[1], i)
                            found = True
                    if not found:
                        nodes.append((node1, i))
                        G.add_edge(node1, i)
                        
                        G.add_node(i)

# Get the connected components
components = list(nx.connected_components(G))
# z = [('Douglas G Altman', 'B. Gersh')]

# Plot each component
if len(components) == 1:
    fig, ax = plt.subplots()
    subgraph = G.subgraph(components[0])
    pos = nx.spring_layout(subgraph)

    # Draw nodes
    nx.draw_networkx_nodes(subgraph, pos, ax=ax, node_color='blue', node_size=100, label=True)

    # Draw edges
    nx.draw_networkx_edges(subgraph, pos, ax=ax, edge_color='grey', width=1)

    # Set axis labels
    ax.set_xlabel('X')
    ax.set_ylabel('Y')

    # Perform analysis between nodes
    # for node_pair in z:
    #     node1, node2 = node_pair
    #     try:
    #         undirected_subgraph = subgraph.to_undirected()
    #         dijkstra_path = nx.dijkstra_path(undirected_subgraph, source=node1, target=node2)
    #         print(f"Dijkstra's Algorithm between {node1} and {node2}:")
    #         print(dijkstra_path)
    #     except NetworkXNoPath:
    #         print(f"No path between {node1} and {node2}")

else:
    fig, axes = plt.subplots(len(components), 1, figsize=(10, 4 * len(components)))

    # Plot each component
    for i, component in enumerate(components):
        ax = axes[i]
        subgraph = G.subgraph(component)
        pos = nx.spring_layout(subgraph)

        # Draw nodes
        nx.draw_networkx_nodes(subgraph, pos, ax=ax, node_color='blue', node_size=10, label=True)

        # Draw edges
        nx.draw_networkx_edges(subgraph, pos, ax=ax, edge_color='grey', width=1)

        # Set axis labels
        ax.set_xlabel('X')
        ax.set_ylabel('Y')
        # Perform analysis between nodes
        # for node_pair in z:
        #     node1, node2 = node_pair
        #     if any(node[0] == node1 for node in nodes):
        #         if any(node[1] == node2 for node in nodes):
        #             try:
        #                 undirected_subgraph = subgraph.to_undirected()
        #                 dijkstra_path = nx.dijkstra_path(undirected_subgraph, source=node1, target=node2)
        #                 print(f"Dijkstra's Algorithm between {node1} and {node2}:")
        #                 print(dijkstra_path)
        #             except NetworkXNoPath:
        #                 print(f"No path between {node1} and {node2}")
        #         else:
        #             print(f"Node {node2} doesn't exist")
        #     else:
        #         print(f"Node {node1} doesn't exist")

plt.show()

nx.edge_betweenness_centrality(G)

nx.density(G)
# density(G) = (2 * num_edges) / (n * (n - 1))



# print(G.nodes)
# print(G.number_of_nodes())
# nx.edge_betweenness_centrality(G)
# Calculate edge betweenness centrality
edge_betweenness = nx.edge_betweenness_centrality(G)

# Find the edges with the highest betweenness centrality
max_betweenness = max(edge_betweenness.values())
edges_with_max_betweenness = [edge for edge, centrality in edge_betweenness.items() if centrality == max_betweenness]

# Print the edges with the highest betweenness centrality
# print("Edges with highest betweenness centrality:")
# for edge in edges_with_max_betweenness:
#     print(edge,nx.edge_betweenness_centrality(G)[edge])



plt.title('Without Delete and Number of communities %s'%(nx.number_connected_components(G)), fontsize=20)

nx.draw(G, with_labels=True, node_color='r')
plt.show()
degrees = [(node,val) for (node, val) in G.degree()]
sorted(degrees, key=lambda x: x[1], reverse=True)
print(degrees)
communities = nx.connected_components(G)

# Iterate over each community
for community in communities:
    # Create a subgraph for the current community
    subgraph = G.subgraph(community)
    
    # Calculate the degrees of nodes in the subgraph
    degrees = subgraph.degree()
    
    # Find the node with the highest degree
    max_degree_node = max(degrees, key=lambda x: x[1])
    
    # Print the node with the highest degree in the current community
    print("Community:", community)
    print("Node with highest degree:", max_degree_node[0])
    print("Degree:", max_degree_node[1])

    # Plot the subgraph with the node highlighted
    nx.draw(subgraph, with_labels=True, node_color='r', nodelist=[max_degree_node[0]])
    plt.title('Community: {}  Node: {}'.format(community, max_degree_node[0]), fontsize=20)
    plt.show()
# NUM_ITERATIONS = 2
# for i in range(NUM_ITERATIONS):
#     edge_betweenness = nx.edge_betweenness_centrality(G).items()
#     edge_to_delete = sorted(edge_betweenness, key=lambda pair: -pair[1])[0][0]
    
#     G.remove_edge(*edge_to_delete)
    
#     nx.draw(G, with_labels=True, node_color='r')
#     plt.title('Step %s\nEdge %s Deleted  Number of communities %s'%(i, edge_to_delete,nx.number_connected_components(G)), fontsize=20)
    
#     plt.show()

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np

# Create an example graph

# Calculate the degree sequence
degree_sequence = sorted([d for n, d in G.degree()], reverse=True)
dmax = max(degree_sequence)

# Create the figure and subplots
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8))

# Degree sequence plot
ax1.plot(degree_sequence, 'b-', marker='o')
ax1.set_title('Degree Rank Plot')
ax1.set_xlabel('Rank')
ax1.set_ylabel('Degree')

# Degree histogram
hist, bins, _ = ax2.hist(degree_sequence, bins=range(dmax + 2))
ax2.set_title('Degree Histogram')
ax2.set_xlabel('Degree')
ax2.set_ylabel('# of Nodes')

# Update the x-axis ticks and labels for the histogram
ax2.set_xticks(bins[:-1])
ax2.set_xticklabels(bins[:-1])

# Adjust spacing between subplots
fig.tight_layout()

# Display the plots
plt.show()

degree_dict = dict(G.degree())
max_degree = max(degree_dict.values())
highest_degree_nodes = [node for node, degree in degree_dict.items() if degree == max_degree]
for node in highest_degree_nodes:

  print("Nodes with the highest degree:", highest_degree_nodes,degree_dict[node])

clustering_coefficient = nx.algorithms.cluster.clustering(G)
av_clustering_coefficient = sum(clustering_coefficient.values())/len(clustering_coefficient)
plt.hist(clustering_coefficient.values(), label ='clustering_coefficient')
plt.axvline(av_clustering_coefficient, color ='r', linestyle = 'dashed', label= 'av_clustering_coefficient')
plt.legend()
plt.ylabel('number of nodes')
plt.title('clustering coefficient')
plt.show()

import community.community_louvain as community
import matplotlib.cm as cm
import matplotlib.pyplot as plt

# load the karate club graph

#first compute the best partition
partition = community.best_partition(G)
print(partition.items())
# draw the graph
pos = nx.spring_layout(G)
# color the nodes according to their partition
cmap = cm.get_cmap('viridis', max(partition.values()) + 1)
nx.draw_networkx_nodes(G, pos, partition.keys(), node_size=40,
                       cmap=cmap, node_color=list(partition.values()))
nx.draw_networkx_edges(G, pos, alpha=0.5)
plt.show()

#######################

from networkx.exception import NetworkXNoPath

# Read the CSV file
nodes = []
G = nx.Graph()

with open('test31.csv', 'r', encoding='utf-8') as file:
    csv_reader = csv.reader(file)
    next(csv_reader)  # Skip the header row
    for row in csv_reader:
        author = row[1]
        if author:
            node1 = author
            node2 = row[7]
            if node2:
                names = [name.strip("'") for name in node2.split(", ")]
                for i in names:
                    if i and node1:
                        found = False
                        for n in nodes:
                            if n[1] == node1:
                                G.add_edge(n[1], i)
                                found = True
                                break
                        if not found:
                            nodes.append((node1, i))

# Create an undirected graph

# Add nodes and edges to the graph
G.add_edges_from(nodes)

# Degree distribution analysis
degrees = dict(G.degree())
degree_values = sorted(set(degrees.values()))
degree_counts = [list(degrees.values()).count(deg) for deg in degree_values]

# Plot the degree distribution
plt.plot(degree_values, degree_counts, 'ro-')
plt.xlabel('Degree')
plt.ylabel('Count')
plt.title('Degree Distribution')
plt.show()
